version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pswdrd123
    volumes:
         - ./pgdata:/var/lib/postgresql/data
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
      
  user-management-service:
    build: ./user-management-service/
    ports:
      - "8001:8000"
    volumes:
      - ./user-management-service/app:/usr/src/app      
  
  experience-service:
    build: ./experience-service/
    ports:
      - "8088:8000"
    volumes:
      - ./experience-service/app:/usr/src/app